{% set name = "harissa" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f7e6e2b7d06c57b3dd7a73c63d86e74d815d62a7228aaaa06dac31c9aeaa2e1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26
    - scipy >=1.13
    - numba >=0.60
    - matplotlib-base >=3.8
    - networkx >=3.3

test:
  imports:
    - harissa
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ulysseherbach/harissa
  doc_url: https://ulysseherbach.github.io/harissa
  summary: Simulation and inference of gene regulatory networks based on transcriptional bursting
  description: |
    Integrated set of tools to perform mechanistic simulation and inference
    of gene regulatory networks from single-cell data, based on stochastic
    gene expression driven by the transcriptional bursting phenomenon.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ulysseherbach
    - nseyler1
